"""Create shops table

Revision ID: 4696160692c1
Revises: 0d5e3b33df6d
Create Date: 2023-06-15 01:47:27.575905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4696160692c1'
down_revision = '0d5e3b33df6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
